version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.3
  - dependency-name: mockery/mockery
    versions:
    - 1.4.3
