version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4
    container_name: laravel_travelperk_app
    entrypoint: "composer update"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    tty: false
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - vendor:/usr/src/app/vendor

volumes:
  vendor:
